services:
  presensi-app:
    build:
      context: /mnt/ssd/hosting/presensi-app
    container_name: presensi-app
    restart: unless-stopped
    env_file:
      - /mnt/ssd/hosting/presensi-app/.env
    environment:
      TZ: Asia/Jakarta
      PRESENSI_DB_PATH: /app/data/presensi.db
    volumes:
      - /mnt/ssd/hosting/presensi-app:/app
      - /mnt/ssd/hosting/presensi-app/data:/app/data
      - /mnt/ssd/hosting/presensi-app/uploads:/app/uploads
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "5050:5050"
    networks:
      - hosting_web

  cloudflared-presensi:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-presensi
    restart: unless-stopped
    environment:
      TUNNEL_TOKEN: "eyJhIjoiZjlmMTU0YzMyZDI0NDYyZTU2MmFmNWMwY2JlZjBkZTkiLCJ0IjoiZTdjZWU1NjktYjhiNC00OWFjLTlkZmYtOWNlMjgwZTE4ZDE2IiwicyI6IlpUYzJaR0poTVdJdE56a3paUzAwWW1ZM0xXRTFOekV0WkRCaU9HVTBNbUV3TXpSaiJ9"
    command: tunnel --no-autoupdate --config /etc/cloudflared/config.yml run
    volumes:
      - /mnt/ssd/hosting/cloudflared-presensi:/etc/cloudflared
    depends_on:
      - presensi-app
    networks:
      - hosting_web
